### ISSUE TITLE
iCloudpd Unraid. Flat hierarchy and deleting

### ISSUE THREAD

**Issue by data-source** [Womabre/unraid-docker-templates#20]
Synchronisation is working fine.  
However two items are bugging me.  
Tried to set 'Folder Structure' to 'album' but it did nothing. 
Had to revert to {:%Y/%Y-%m-%d}

I also have all files within folders in duplicate. Both HEIC and jpg. 
Tried to set this to true: 
Container Variable: delete_accompanying
"Tells the script to delete files which accompany the HEIC files that are downloaded. These are the JPG files which are created if you have HEIC to JPG conversion enabled. They are also the _HEVC.MOV files which make up part of a live photo." 

But likewise didn't work. 

How do I : 
-Keep hierarchy as 'ALBUM NAME' 
-Convert HEIC to JPG and also delete HEIC

Thank you

**Comment by Womabre** [comment]
Please refer to documentation of [docker-icloudpd](https://github.com/boredazfcuk/docker-icloudpd/blob/master/CONFIGURATION.md)
This is only the template for unraid.
