### ISSUE TITLE
container stops, cannot run script to update 2FA cookie expiry 

### ISSUE THREAD

**Issue by lmacfarlan** [Womabre/unraid-docker-templates#5]
When I run the latest container, I'm not able to get into the system while it's running to update my 2FA. Been running older versions just fine. 

`2021-06-24 16:44:43 INFO Sync user user`

`2021-06-24 16:44:43 INFO Check 2FA Cookie`

`2021-06-24 16:44:43 INFO Cookie exists, check expiry date`

`2021-06-24 16:44:43 ERROR Cookie has expired. Please run container interactively to generate - Retry in 5 minutes`

**Comment by d-underhill** [comment]
remove the "apple_password" from the settings of the container and apply changes.  Then start the container and run the following from the terminal:  docker exec -it icloudpd sync-icloud.sh --Initialise

You should then be prompted for 2FA.

**Comment by lmacfarlan** [comment]
Ok I dumped the variable but I can't get the --initialize command in before the container exits.

What am I missing?

edit: Fixed. Closing issue. After removing the option from the container, and waiting a day or so it worked. I may have hit a rate limiter on Apple's 2FA.

**Comment by sgraaf** [comment]
For anyone still struggling with this issue, running this in the terminal worked for me:
```bash
docker start icloudpd && docker exec -it icloudpd sync-icloud.sh --Initialise
```
